name: Generate Stats Cards

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: IanLiYi1996
          BRANCH_NAME: stats
          UTC_OFFSET: 8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
